### PR TITLE
Chat 1 - Users can create conversations

### PR DESCRIPTION
**Pull request by tugushka**
When someone creates a new conversation, every invitees and the host will get userConversation entity on the datastore.
**Removed the chat request completely**

### CODE REVIEW

**Comment by Byambaa0325** [comment]
Hi, I see a lot of re-edits in the commits, where you added one thing in the first commits then went on to delete or edit those. Do you think maybe you can do separate PR's feature by feature? Following general guideline, you could make each PR to take about no more than 100 lines or 15 mins. Alternatively, you can walk me through the code, if you prefer. At its current size and commit structure, I think we may not be able to do quality code review :)

**Review by Byambaa0325 — CHANGES_REQUESTED** [review]
See above comment

**Comment by tugushka** [comment]
> See above comment

In this pull request, I implemented 3 things
1. Chat html
2. Conversation creator with different people (by their email 🤷)
3. Display user's invited/involved conversations.

At the beginning I planned to have invitation requests for invitee, but after discussing with Huygaa ah, I decided to drop it.

Currently, the chat creates 2 entities: Conversation and UserConversation.
When new conversation is created by the user, then new Conversation entity is added with unique id (Conversation id -> convid). After the conversation is added to the db, we have to add people to it. So for every invitee and the conversation creator will get new userConversation entity with convid.

In addition, if I want to get all conversation of the user I'll query userConversation entity from db matches the email of the user.

**Review by Byambaa0325 — APPROVED** [review]
Generally, seems fine and working.

**Pull request merged**
